Added behavior implementation for lazy load handling.
MaritzSTL/lazy-imports-handler-behavior pull request #1
Opened 2017-07-10 03:54 UTC by haydenmcp

+ Added tests.
    + Note: One test fails on Chrome related to the Shadow DOM implementation and how bubbling occurs. 
    This test will be fixed once the issues with Shadow DOM are resolved. Google has been contacted and is 
    investigating.
+ Added demo.

2017-07-10 06:03 UTC, stramel requested changes

2017-07-10 06:03 UTC, stramel commented on bower.json
> +    "paper-button": "PolymerElements/paper-button#^2.0.0",
`paper-button` should be using a version range here. `^1.0 || ^2.0`

2017-07-10 06:03 UTC, stramel commented on bower.json
> +    "paper-button": "PolymerElements/paper-button#^2.0.0",
`paper-button` should be in the `devDependency` section

2017-07-10 06:03 UTC, stramel commented on bower.json
> +    "paper-button": "PolymerElements/paper-button",
Replace this with the one from `dependencies` + changes.

2017-07-10 06:03 UTC, stramel commented on bower.json
> +    "lazy-imports": "Polymer/lazy-imports",
`lazy-imports` is a dependency, it doesn't need to be listed as a dev dependency

2017-07-10 06:03 UTC, stramel commented on demo/high-level-element.html
> +<link rel="import" href="./intermediate-element.html">
`./` isn't needed.

2017-07-10 06:03 UTC, stramel commented on demo/high-level-element.html
> +<dom-module id='high-level-element'>
NIT: Generally, we prefer double quotes.

2017-07-10 06:03 UTC, stramel commented on demo/index.html
> +    <link rel="import" href="./high-level-element.html">
`./` isn't necessary.

2017-07-10 06:03 UTC, stramel commented on demo/magical-button.html
> +<link rel="import" href="../../paper-styles/color.html">
Remove color import. It is just adding bloat to load and isn't being used

2017-07-10 06:03 UTC, stramel commented on demo/magical-button.html
> +<link rel="import" href="../../lazy-imports/lazy-imports-behavior.html">
Remove `lazy-imports` import.

2017-07-10 06:03 UTC, stramel commented on demo/magical-button.html
> +<link rel="import" href="../../paper-button/paper-button.html">
Could also get rid of `paper-button` completely by just using `button` here.

2017-07-10 06:03 UTC, stramel commented on demo/magical-button.html
> +          bubbles: true,
I don't think `bubbles` is necessary here since we are using the capture phase.

2017-07-10 06:03 UTC, stramel commented on demo/index.html
> +          <high-level-element id="high-level-element"></high-level-element>
Remove `id` here

2017-07-10 06:03 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> +    /** Import lazy group provided that the domain of the group matches the registered domain
Start documentation on next line of block comment.

2017-07-10 06:03 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> +     */
Missing `@protected`

2017-07-10 06:03 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> +      const {detail} = event;
```js
const {detail={}} = event;
if (detail.group && detail.domain === this.domain) {
```

2017-07-10 06:03 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> +mtz.LazyImportsHandlerBehavior = [Polymer.LazyImportsBehavior, LazyImportsHandlerBehaviorImpl];
This needs a comment of:

`/* @polymerBehavior */`

2017-07-10 06:03 UTC, stramel commented on test/1.x/lazy-element.html
> +<!--
Remove this file and the 1.x folder.

2017-07-10 06:03 UTC, stramel commented on test/element-using-lazy-import.html
> +    <link rel="import" href="../../polymer/polymer.html">
Fix spacing of these imports.

2017-07-10 06:03 UTC, stramel commented on test/index.html
> +
NIT: Remove empty line.

2017-07-10 06:03 UTC, stramel commented on test/mtz-lazy-imports-handler-behavior_test.html
> +    <link rel="import" href="nested-element-using-lazy-import.html">
Remove import for nested element.

2017-07-10 06:03 UTC, stramel commented on test/mtz-lazy-imports-handler-behavior_test.html
> +            bubbles: true,
I don't think `bubbles` is necessary

2017-07-10 06:03 UTC, stramel commented on test/mtz-lazy-imports-handler-behavior_test.html
> +            // FIXME: Issue with shadow DOM experienced in this test so dispatch is done
Add your initials and a JIRA ticket # so we can track it.

2017-07-10 06:03 UTC, stramel commented on test/mtz-lazy-imports-handler-behavior_test.html
> +            it('should not handle event without defined domain', () => {
This is a valid case no domain is default. as long as the implementing element didn't set a domain it should be listening on no domain. However, `null !== undefined`

2017-07-10 06:03 UTC, stramel commented on test/nested-element-using-lazy-import.html
> +    <link rel="import" href="../../polymer/polymer.html">
Fix Spacing.

2017-07-10 13:55 UTC, haydenmcp commented on mtz-lazy-imports-handler-behavior.html
> +mtz.LazyImportsHandlerBehavior = [Polymer.LazyImportsBehavior, LazyImportsHandlerBehaviorImpl];
Does that need to be located immediately above the actual assignment? I placed @polymerBehavior in the module description above.

2017-07-10 14:02 UTC, haydenmcp commented on test/mtz-lazy-imports-handler-behavior_test.html
> +            // FIXME: Issue with shadow DOM experienced in this test so dispatch is done
- [ ] Create JIRA ticket and add initials to code.

2017-07-10 14:11 UTC, haydenmcp commented on test/mtz-lazy-imports-handler-behavior_test.html
> +            it('should not handle event without defined domain', () => {
Fixed and added tests verifying those cases.

2017-07-10 14:14 UTC, haydenmcp commented on test/index.html
> +
Interestingly, this line is automatically inserted upon save of the file. lol

2017-07-10 14:39 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> +mtz.LazyImportsHandlerBehavior = [Polymer.LazyImportsBehavior, LazyImportsHandlerBehaviorImpl];
It needs to be placed here as well as at the impl with the name on the impl. Just add what I posted here.

2017-07-10 14:39 UTC, stramel commented on test/index.html
> +
It shouldn't be auot-inserted unless it is the end of file

2017-07-10 15:50 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> + * @polymerBehavior mtz.LazyImportsHandlerBehavior
Remove `mtz.` from here.

2017-07-10 18:22 UTC, stramel requested changes

2017-07-10 18:22 UTC, stramel commented on demo/high-level-element.html
> +  <link rel='lazy-import' group='gryffindor' href='demo-element-one.html'>
- [ ] Switch all HTML `'` to `"`

2017-07-10 18:22 UTC, stramel commented on demo/magical-button.html
> +        const lazyImportGroupEvent = new CustomEvent('import-lazy-group', options);
I would inline this into dispatch since you are creating options outside of it, or move options into this constructor.

2017-07-10 18:22 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> +      if (detail && detail.group && this.domain !== null && this.domain === detail.domain) {
`detail.group && detail.domain === this.domain`

2017-07-10 19:29 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> +      if (detail && detail.group && this.domain === detail.domain) {
Don't need `detail` check here since we are defaulting it now

2017-07-10 19:29 UTC, stramel commented on mtz-lazy-imports-handler-behavior.html
> +      if (detail && detail.group && this.domain === detail.domain) {
Don't need the `detail` check here anymore since we are defaulting it now

2017-07-10 21:06 UTC, stramel submitted a review, later dismissed

2017-07-11 16:49 UTC, admwx7 commented on demo/index.html
> +          <high-level-element></high-level-element>
This shows up as the snippet on how to create your element, just showing this as the snippet is useless for implementation details, you should instead inline the definition for this element here so it shows up as the snippet on the demo page, makes it easier for our user's to reproduce.

2017-07-11 16:49 UTC, admwx7 commented on mtz-lazy-imports-handler-behavior.html
> +    /** Import lazy group provided that the domain of the group matches the registered domain
Next line this if you would:
```
/**
 * <description>
```

2017-07-11 16:49 UTC, admwx7 commented on mtz-lazy-imports-handler-behavior.html
> +      if (detail.group && this.domain === detail.domain) {
Checking on `detail.group` here is going to block all following elements from being able to import anything on the same domain, instead we are going to need to run something like:
```
const links = Array.from(Polymer.dom(this).localName.
  querySelectorAll(`link[rel=\'lazy-import\'][href]:not([href=\'\']`));
this.groups = new Set(links.map((link) => {
  return link.getAttribute('group') || '';
}));
```
in the ready() lifecycle and build out a list of groups this element has, then check the group to see if it's contained in our array of groups.  Note the above logic supports the case of having no group attribute (stored in the Set as an empty string) this is intentional and gives us a way to track that our element has a lazy-import for a link that without a group.

2017-07-11 16:49 UTC, admwx7 commented on test/element-using-lazy-import.html
> +      is: 'element-using-lazy-import',
There's no need to duplicate elements between your test and demo folders, I create them once in my demo folder in a way that serves my demo requirements then use those same elements in my tests.

2017-07-11 16:49 UTC, admwx7 commented on test/mtz-lazy-imports-handler-behavior_test.html
> +            flush(() => {
Based on your next beforeEach statement, is this flush needed?

2017-07-11 16:49 UTC, admwx7 commented on test/mtz-lazy-imports-handler-behavior_test.html
> +              sinon.spy(event, 'stopImmediatePropagation');
`const spy = ...` then below you can `expect(spy).not.to.be.called;`

2017-07-11 16:49 UTC, admwx7 commented on test/mtz-lazy-imports-handler-behavior_test.html
> +              sinon.spy(element, '_importLazyGroup');
If you want to prevent default logic (speeds up your tests in most cases) then you can do: `element._importLazyGroup = sinon.spy();`

With the layout you have now it will go ahead an log that it was called like a spy but then call through to the intended logic and load things, just a little optimization to speed up test times if you don't actually care about the logic running.

2017-07-11 18:07 UTC, haydenmcp commented on mtz-lazy-imports-handler-behavior.html
> +      if (detail.group && this.domain === detail.domain) {
- [ ] Implement child lazy imports finding.

2017-07-11 19:22 UTC, haydenmcp commented on test/mtz-lazy-imports-handler-behavior_test.html
> +              sinon.spy(event, 'stopImmediatePropagation');
I implemented it as...
sinon.spy(obj, 'fcnName');
expect(obj.fcnName).not.to.be.called;
Do you have any objections to that? I like that it conveys to the reader which object function should have been called.

2017-07-11 19:28 UTC, haydenmcp commented on test/mtz-lazy-imports-handler-behavior_test.html
> +            flush(() => {
Interestingly, this is the flush that firefox required for Polymer 1.x. Without it, the tests fail. So, it is needed. But unfortunately I don't understand why. I know we talked about the async model of firefox and how it differs from chrome. I need to research that to further understand.

2017-07-11 21:25 UTC, haydenmcp commented on test/element-using-lazy-import.html
> +      is: 'element-using-lazy-import',
Is there a way in which I can unravel a demo element that's defined in another file?

2017-07-12 15:00 UTC, stramel submitted a review, later dismissed

2017-07-12 19:48 UTC, admwx7 requested changes

2017-07-12 19:48 UTC, admwx7 commented on demo/index.html
> +                  this.domain = 'hogwarts';
```
properties: {
  domain: {
    type: String,
    value: 'hogwarts'
  }
}
```

2017-07-12 19:48 UTC, admwx7 commented on demo/index.html
> +                  this.dispatchEvent(new CustomEvent('import-lazy-group', {
You should add a demo-element-three, or paper-input for example, on a different group namespace that can be fired based on a different button so they can see it being imported at this level as well.

2017-07-12 19:48 UTC, admwx7 commented on mtz-lazy-imports-handler-behavior.html
> +        value: ''
This always has to be set by the implementer, so I wouldn't provide a default value here, just means observers trigger when they shouldn't.

2017-07-12 19:48 UTC, admwx7 commented on mtz-lazy-imports-handler-behavior.html
> +      groups: {
Make this private instead, its just for our internal use.  Should also be readOnly.

2017-07-12 19:48 UTC, admwx7 commented on mtz-lazy-imports-handler-behavior.html
> +        value() {
Either keep this function and perform the set logic here, or drop this and do it in the ready statement, but you shouldn't have both.

2017-07-12 19:48 UTC, admwx7 commented on mtz-lazy-imports-handler-behavior.html
> +    _isValidDomain(domain) {
Nitpicky, but this seems excessive for doing `===` logic in a single location.

2017-07-12 19:48 UTC, admwx7 commented on test/mtz-lazy-imports-handler-behavior_test.html
> +        describe('ready()', () => {
Just an observation / FYI, the most accurate way of testing ready would be to run `document.createElement('high-level-element');` reason being is that creation is the trigger for ready logic, by the time element is available in these tests using fixture it's also run the attached() lifecycle event.

2017-07-13 00:23 UTC, admwx7 requested changes

2017-07-13 00:23 UTC, admwx7 commented on mtz-lazy-imports-handler-behavior.html
> +        groups = new Set(links.map((link) => {
To avoid allocating space in the heap for the same object twice (`new Set()`) instead of creating a second new set here, loop through using `forEach` instead of `map` and run `groups.add(link.getAttribute('group') || ''` this also lets you change `groups` to be a `const`.

2017-07-13 00:33 UTC, admwx7 commented on mtz-lazy-imports-handler-behavior.html
> +        groups = new Set(links.map((link) => {
On second thought, you should update this logic to:
```
this.__groups = new Set(
  Array.from(Polymer.DomModule.import(this.localName).
  querySelectorAll(`link[rel=\'lazy-import\'][href]:not([href=\'\']`)).
  map((link) => link.getAttribute('group') || ''));
```
This logic can't be run without a DomModule so we don't need to validate that it exists, which removes the need to create the extra variables all together.

2017-07-13 02:59 UTC, haydenmcp commented on mtz-lazy-imports-handler-behavior.html
> +        groups = new Set(links.map((link) => {
Added in those changes and wrapped tests around them.

2017-07-13 15:18 UTC, admwx7 submitted a review, later dismissed

2017-07-13 17:32 UTC, admwx7 approved these changes

2017-07-13 22:39 UTC, stramel approved these changes

2017-07-13 22:54 UTC, merged